---
title: "Terremotos y HTML Widgets"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: ["twitter", "linkedin"]
---

```{r setup, include=FALSE}
library(formattable)
library(flexdashboard)
library(readr)
library(dplyr)
library(leaflet)
library(crosstalk)
library(DT)
```


```{r data}
## leer archivo y guardarlo en una variable
earthquakedata <- read_csv("data/earthquakedata.csv")
## desde internet solo pongo elm link

```

# STATICO {data-icon=fa-chalkboard}

## row

### columna
```{r}
earthquakedata %>%
  filter(yr == 1995) %>%
  DT::datatable()
```

### columna
```{r}
## agregando la data, agregando los labels, 
earthquakedata %>%
  filter(yr == 1995) %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~lon,
             lat = ~lat,
             label = ~yr)
```

# DINAMICO (crosstalk) {data-icon=fa-rocket}

```{r}
data_shared <- SharedData$new(earthquakedata %>%
                                filter(yr > 2000))
```
### Filtros
```{r}
filter_select("yr", "Año", data_shared, group = ~yr, multiple = FALSE)

```
## Data
### datos 

```{r}
data_shared %>%
  DT::datatable()
```


### mapa
```{r}
## agregando la data, agregando los labels, 
data_shared %>%
  leaflet() %>%
  addTiles() %>%
  addMarkers(lng = ~lon,
             lat = ~lat,
             label = ~yr)
```
